server:
  port: 8888

spring:
  application:
    name: githubConfigServer

  cloud:
    config:
      server:
        git:
          uri: https://github.com/KoksharovSA/ConfigRepository.git
          basedir: file://c:/tmp/SpringCloud
          default-label: main