server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/gb
    username: postgres
    password: Se656658rg19
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: productApp

  profiles:
    active: eclient

  config:
    import: configserver:http://localhost:8888

management:
  endpoints:
    web:
      exposure:
        include:
          - metrics
          - prometheus
          - health
  endpoint:
    health:
      show-details: always